import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/shared/Footer";
// import Nav from "@/components/shared/Nav";
import { SpeedInsights } from "@vercel/speed-insights/next"
import NavigationBar from "@/components/shared/NavigationBar";
import Nav2 from "@/components/shared/Nav2";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Graduate Consultancy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {/* <Nav></Nav> */}
        <Nav2></Nav2>
        <NavigationBar></NavigationBar>
        {children}
        <Footer></Footer>
        <SpeedInsights />
      </body>
    </html>
  );
}
